version: '3.1'
services:

  nginx:
    container_name: Controller
    build:
      context: .
      dockerfile: ./src/controller/Dockerfile
    image: docker.pkg.github.com/fub-hcc/ikon-backend/controller:latest
    ports:
      - "443:443"
      - "80:80"
      - "8080:80"
    secrets:
      - ssl_key
      - ssl_crt

  mwc:
    container_name: MediaWikiConnector
    build:
      context: ./src/mwc/
      dockerfile: Dockerfile
    image: docker.pkg.github.com/fub-hcc/ikon-backend/mwc:latest
    ports:
      - "5434:443"
    environment:
      IKONCODE: /run/secrets/ikoncode_secrets
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt
      - ikoncode_secrets

  logging:
    container_name: LoggingService
    build:
      context: ./src/logging/
      dockerfile: Dockerfile
    volumes:
      - ./src/logging/data/log.txt:/usr/src/app/log.txt
    image: docker.pkg.github.com/fub-hcc/ikon-backend/logging:latest
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt

  topicextraction:
    container_name: TopicExtractionService
    build:
      context: ./src/topicextraction/
      dockerfile: Dockerfile
    image: docker.pkg.github.com/fub-hcc/ikon-backend/tes:latest
    ports:
      - "5435:443"
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    volumes:
      - ./src/topicextraction/src:/app
      - ./assets/models:/models
    secrets:
      - ssl_key
      - ssl_crt

  bertikon:
    container_name: BERTaaSIKON
    build:
      context: .
      dockerfile: ./src/bert/Dockerfile
    image: docker.pkg.github.com/fub-hcc/ikon-backend/bertikon:latest
    volumes:
      - ./assets/models/bert:/model

  sharing:
    container_name: SharingService
    build:
      context: ./src/sharing/
      dockerfile: Dockerfile
    image: docker.pkg.github.com/fub-hcc/ikon-backend/sharing:latest
    ports:
      - "5436:443"
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    volumes:
      - ./src/sharing/src:/app
    secrets:
      - ssl_key
      - ssl_crt

secrets:
  ssl_crt:
    file: ./assets/ssl/server.crt
  ssl_key:
    file: ./assets/ssl/server.key
  ikoncode_secrets:
    file: ./assets/secrets/ikoncode_secrets
