version: '3.1'
services:

  nginx:
    container_name: Controller
    build:
      context: .
      dockerfile: ./src/controller/Dockerfile
    image: ikonresearch/controller:latest
    ports:
      - "443:443"
      - "80:80"
    secrets:
      - ssl_key
      - ssl_crt

  mwc:
    container_name: MediaWikiConnector
    build:
      context: ./src/mwc/
      dockerfile: Dockerfile
    image: ikonresearch/mwc:latest
    ports:
      - "5434:443"
    environment:
      IKONCODE: /run/secrets/ikoncode_secrets
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt
      - ikoncode_secrets

  topicextraction:
    container_name: TopicExtractionService
    build:
      context: ./src/topicextraction/
      dockerfile: Dockerfile
    image: ikonresearch/tes:latest
    ports:
      - "5435:443"
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt

  sharing:
    container_name: SharingService
    build:
      context: ./src/sharing/
      dockerfile: Dockerfile
    image: ikonresearch/sharing:latest
    ports:
      - "5436:443"
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt

secrets:
  ssl_crt:
    file: ./assets/ssl/server.crt
  ssl_key:
    file: ./assets/ssl/server.key
  ikoncode_secrets:
    file: ./assets/secrets/ikoncode_secrets
