version: '3.1'
services:

  notebook:
    container_name: NLPNotebook
    build:
      context: .
      dockerfile: ./src/topicextraction/nlp/Dockerfile.cpu
    volumes:
      - ./src/topicextraction/nlp:/tf/notebooks
      - ./assets/data/nlp:/tf/data
    ports:
      - "5436:8888"
    user: ${CURRENT_UID}
    depends_on:
      - postgres
    environment:
      PG_PASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres_password