version: '2'
services:

  controller:
    build:
      context: src/controller/
    ports:
     - "80:7777"

  postgres:
    build:
      context: src/postgres/
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres

  dal:
    build:
      context: src/dal
    depends_on:
      - postgres

  clustering:
    build: src/clustering
    depends_on:
      - dal



  web:
    build: .

    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]
