version: '3.1'
services:

  postgres:
    container_name: Postgres
    build:
      context: .
      dockerfile: /src/postgres/Dockerfile
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ikon
    secrets:
      - postgres_password

  dal:
    container_name: DataAccessLayer
    build:
      context: ./src/dal/
      dockerfile: Dockerfile
    ports:
      - "5433:8080"
    environment:
      PGUSER: pguser
      PGHOST: postgres
      PGDATABASE: ikon
      PGPORT: 5432
    secrets:
      - postgres_password
      - ssl_key
      - ssl_crt
      - geocoding_api_key

  rabbitmq:
    image: rabbitmq:latest
    container_name: RabbitMQ
    ports:
      - 5672:5672
    environment:
      RABBITMQ_SSL_KEY_FILE: /run/secrets/ssl_key
    secrets:
      - postgres_password
      - ssl_key
      - ssl_crt
      - geocoding_api_key

secrets:
  postgres_password:
    file: ./assets/IKON-backend-config/secrets/postgres_password
  geocoding_api_key:
    file: ./assets/IKON-backend-config/secrets/geocoding_api_key
  ssl_crt:
    file: ./assets/ssl/server.crt
  ssl_key:
    file: ./assets/ssl/server.key

