version: '3.1'
services:

  nginx:
    container_name: Controller
    build:
      context: .
      dockerfile: ./src/controller/Dockerfile
    ports:
      - "443:443"
    secrets:
      - ssl_key
      - ssl_crt

  postgres:
    container_name: Postgres
    build:
      context: .
      dockerfile: ./src/postgres/Dockerfile
    volumes:
      - ikon_database:/var/lib/postgresql/data:z
      - ./assets/data/gepris:/dump_data/gepris
      - ./assets/data/data_augmentation/:/dump_data/data_augmentation
      - ./assets/data/project_input:/dump_data/project_input
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ikonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ikon
      PGDATA: /usr/postgresql/data
    secrets:
      - postgres_password

  dal:
    container_name: DataAccessLayer
    build:
      context: ./src/dal/
      dockerfile: Dockerfile
    ports:
      - "5433:443"
    depends_on:
      - postgres
      - mwc
    environment:
      PGUSER: ikonuser
      PGHOST: Postgres
      PGDATABASE: ikon
      PGPORT: 5432
      PORT: 443
    secrets:
      - postgres_password
      - ssl_key
      - ssl_crt

  mwc:
    container_name: MediaWikiConnector
    build:
      context: ./src/mwc/
      dockerfile: Dockerfile
    ports:
      - "5434:443"
    environment:
      IKONCODE: /run/secrets/ikoncode_secrets
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PORT: 443
    secrets:
      - ssl_key
      - ssl_crt
      - ikoncode_secrets

  topicextraction:
    container_name: TopicExtractionService
    build:
      context: ./src/topicextraction/
      dockerfile: Dockerfile
    ports:
      - "5435:443"
    environment:
      SSL_KEY: /run/secrets/ssl_key
      SSL_CRT: /run/secrets/ssl_crt
      PG_PASSWORD: /run/secrets/postgres_password
      PORT: 443
    volumes:
      - ./src/topicextraction/nlp/dumps:/data
    secrets:
      - ssl_key
      - ssl_crt
      - postgres_password

secrets:
  postgres_password:
    file: ./assets/secrets/postgres_password
  ssl_crt:
    file: ./assets/ssl/server.crt
  ssl_key:
    file: ./assets/ssl/server.key
  ikoncode_secrets:
    file: ./assets/secrets/ikoncode_secrets

volumes:
    ikon_database:
        external: false
