version: '3'
services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080