openapi: "3.0.0"
info:
  version: 1.0.0
  title: IKON backend
  license:
    name: APGL V3.0
servers:
  - url: https://localhost:5000/api/
paths:
  /projects:
    get:
      summary: Get the intial project data
      operationId: getProjects
      tags:
        - projects
      responses:
        '200':
          description: An array of projects
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /institutions:
    get:
      summary: Get the geocoded list of all institutions which are connnected to projects
      operationId: getInstitutions
      tags:
        - institutions
      responses:
        '200':
          description: An array of institutions
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Institutions"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Project:
      properties:
        applicant:
          type: string
        end_date:
          type: string
        research_area:
          type: string
        review_board:
          type: string
        subject_area:
          type: string
        sponsor:
          type: string
        id:
          type: string
        address:
          type: string
        cooperating_institutions:
          type: string
        side_topics:
          type: string
        project_leader:
          type: string
        start_date:
          type: string
        title:
          type: string
        abstract:
          type: string
        href:
          type: string
        region:
          type: array
          items:
            type: string
        synergy:
          type: string
    Projects:
      type: array
      items:
        $ref: "#/components/schemas/Project"
    Institution:
      properties:
        institution_id:
          type: integer
          format: int32
        name:
          type: string
        address:
          type: string
        phone:
          type: string
        fax:
          type: string
        email:
          type: string
        loc:
          type: object
          properties:
            lat:
              type: integer
              format: int32
            lng:
              type: integer
              format: int32
        internet:
          type: string
    Institutions:
      type: array
      items:
        $ref: "#/components/schemas/Institution"
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string